### ISSUE TITLE
Interactive mode breaks after selecting an item

### ISSUE THREAD

**Issue by Amparose** [jfcherng-sublime/SublimeTodoReview#6]
After pressing enter to nav to a TODO in the list (TodoReview: Open Files), when I go back to the TODO buffer it behaves like an ordinary text file and the items are no longer links.

**Comment by jfcherng** [comment]
I can't reproduce this. The view doesn't work indeed after restart ST.

**Comment by Amparose** [comment]
I just tested on a clean ST can't reproduce either. I tracked it down to a conflict with [NeoVintageous](https://github.com/NeoVintageous/NeoVintageous) if I disable it then TodoReview works properly. Unfortunately, I can't live without NeoVintageous so would this issue be in TodoReview or NeoVintageous?

**Comment by jfcherng** [comment]
I have it fixed and released a new version.

**Comment by jfcherng** [comment]
NeoVintageous just changed some view settings which this plugin depends on.

**Comment by Amparose** [comment]
It works! I just felt how much I have missed this plugin!
